name: Deploy (Simple)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ubuntu
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_PATH: /home/ubuntu/wagora-backend/wagora-chat-backend/
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

    steps:
      - name: Start SSH agent and add key
        run: |
          eval $(ssh-agent -s)
          echo "$EC2_SSH_KEY" | tr -d '\r' > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          ssh-add /tmp/ssh_key

      - name: Disable strict host key checking (optional)
        run: |
          mkdir -p ~/.ssh
          echo "Host $EC2_HOST
                StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/ssh_key -t $EC2_USER@$EC2_HOST << 'EOF'
            pwd
            cd $EC2_PATH
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart all
          EOF

      - name: Remove SSH key
        run: |
          ssh-add -D
          rm -f /tmp/ssh_key